In [1]:
import cv2 
import matplotlib.pyplot as plt 
import os
import numpy as np


In [10]:
def detect_face(img):
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_alt.xml')
        faces = face_cascade.detectMultiScale(gray,scaleFactor=1.2, minNeighbors=5)
        print(faces[0])
        if len(faces)==0:
            return None,None
        (x, y, w, h) = faces[0]
        return gray[y:y+w, x:x+h], faces[0]

In [3]:
def prepare_training_data(data_folder_path):
    dirs = os.listdir(data_folder_path)
    print(dirs)
    faces = []
    labels = []
    for dir_name in dirs:
        if not dir_name.startswith("s"):
            continue
        label = int(dir_name.replace("s", ""))
        subject_dir_path = data_folder_path + "/" + dir_name
        print(subject_dir_path)
        subject_images_names = os.listdir(subject_dir_path)
        print(subject_images_names)
        for image_name in subject_images_names:
            image_path = subject_dir_path+'/'+image_name
            print(image_path)
            image = cv2.imread(image_path)
            face, rect = detect_face(image)
            if face is not None:
                faces.append(face)
                labels.append(label)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    print(faces,labels)
    return faces, labels

In [4]:
f2,l2 = prepare_training_data('resize_a')
face_recognizer = cv2.face.LBPHFaceRecognizer_create()
face_recognizer.train(f2, np.array(l2))

['s1', 's2']
resize_a/s1
['A(1).jpeg', 'A(2).jpeg', 'A(3).jpeg', 'WhatsApp Image 2022-12-15 at 19.49.03.jpeg', 'WhatsApp Image 2022-12-15 at 19.49.09.jpeg', 'WhatsApp Image 2022-12-15 at 19.49.14.jpeg', 'WhatsApp Image 2022-12-15 at 19.49.19.jpeg']
resize_a/s1/A(1).jpeg
[411 203 575 575]
resize_a/s1/A(2).jpeg
[171 444 573 573]
resize_a/s1/A(3).jpeg
[270 280 695 695]
resize_a/s1/WhatsApp Image 2022-12-15 at 19.49.03.jpeg
[190 554 520 520]
resize_a/s1/WhatsApp Image 2022-12-15 at 19.49.09.jpeg
[180 601 536 536]
resize_a/s1/WhatsApp Image 2022-12-15 at 19.49.14.jpeg
[201 592 504 504]
resize_a/s1/WhatsApp Image 2022-12-15 at 19.49.19.jpeg
[198 649 428 428]
resize_a/s2
['WhatsApp Image 2023-01-08 at 23.22.41 (1).jpeg']
resize_a/s2/WhatsApp Image 2023-01-08 at 23.22.41 (1).jpeg
[ 74  82 167 167]
[array([[15, 14, 14, ..., 11, 11, 10],
       [15, 15, 14, ..., 14, 11, 10],
       [16, 15, 14, ..., 15, 11, 10],
       ...,
       [20, 20, 18, ..., 33, 31, 31],
       [15, 17, 19, ..., 31, 28, 2

In [16]:
subjects = ["",  "Basset", "Sajjad_Salam"]
img = cv2.imread("resize_a/s1/A(1).jpeg")
face, rect = detect_face(img)
label= face_recognizer.predict(face)[0]
label_text = subjects[label] 
(x, y, w,  h)  = rect
cv2.rectangle(img, (x,  y),  (x+w,  y+h), (0, 255,  0), 2)
cv2.putText(img, label_text, (rect[0], rect[1]-5), cv2.FONT_HERSHEY_PLAIN,  1.5, (0, 255,  0), 2)
print(label_text)


[406 200 578 578]
Basset
